config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :inquiries
  root "places#index"
  get 'profile', to: 'profile#show'
  get 'search', to: 'search#search'
  resources :places
  resources :plan_your_trips
  resources :tourist_points
  resources :near_by_places
  resources :best_time_to_visits
  resources :how_to_reaches
  resources :car_rentals
  resources :papular_palaces
  resources :popular_places
  
  resources :accommodations do 
    resources :rooms
  end

  namespace :admin do 
    root "dashboard#show"
    get 'profile', to: 'profile#show'
    get 'search', to: 'search#search'
    resources :places
    resources :tourist_points
    resources :near_by_places
    resources :best_time_to_visits
    resources :how_to_reaches
    resources :accommodations
    resources :rooms
    resources :popular_places
    resources :plan_your_trips
    resources :inquiries
    resources :car_rentals do
      collection do
        get :car_all
      end
    end
    resources :rooms do
      member do
        put :approve
        put :unapprove
      end
    end
  end
end

app/models/accommodation.rb
class Accommodation < ApplicationRecord
	has_many_attached :galleries, dependent: :destroy
	has_many :rooms

	validates :name, :city, :state, :address, :pincode, :about, 
			  :contact_number,  presence: true
	# validates :email, presence: true, uniqueness: 
	          {message: "Email must be uniqe "}
	paginates_per 5
end

app/controllers/accommodations_controller.rb
class AccommodationsController < ApplicationController
	
	before_action :set_accommodation, only: %i[ show edit update destroy ]

	def index
     @accommodations = Accommodation.includes(galleries_attachments: :blob).page params[:page]
 	 end

	def show 
	end
	
	private

	def set_accommodation
		@accommodation = Accommodation.find(params[:id])
	end

	def accommodation_paramas
		params.require(:accommodation).permit(:name, :city, :state, :address, :pincode, :about, :contact_number, :email , galleries: [])
	end
end

app/controllers/admin/accommodations_controller.rb
class Admin::AccommodationsController < AdminController
	layout 'admin'

	before_action :set_accommodation, only: %i[ show edit update destroy ]

	def index
     @accommodations = Accommodation.includes(galleries_attachments: :blob).page params[:page]
 	 end

	def new
		@accommodation = Accommodation.new
	end

	def create
		@accommodation = Accommodation.new(accommodation_paramas)
		if @accommodation.save
			redirect_to admin_accommodations_path , notice:"accommodation create succefully"
		else
			render :new
		end 
	end

	def show 
	end

	def edit
	end

	def update
		if @accommodation.update(accommodation_paramas)
			redirect_to admin_accommodations_path , notice:"accommodation update succefully"
		else
			render :edit
		end
	end

	def destroy
		if @accommodation.destroy 
			redirect_to admin_accommodations_path, notice:"accommodation destroy succefully"
		end 
	end

	private

	def set_accommodation
		@accommodation = Accommodation.find(params[:id])
	end

	def accommodation_paramas
		params.require(:accommodation).permit(:name, :city, :state, :address, :pincode, :about, :contact_number, :email , galleries: [])
	end
end

app/helpers/accommodations_helper.rb
module AccommodationsHelper
end

app/views/accommodations/index.html.erb
<div class="col-lg-12">
  <div class="container">
    <div class="row">
      <% if @accommodations.present? %>
       <% @accommodations.each do |accommodation| %>
        <div class="col-lg-6 mt-5">
          <div class="card">
            <% if accommodation.galleries.attached? %>
              <%= image_tag accommodation.galleries.first ,class:"img-fluid", style:"height:350px;max-height:350px" %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= accommodation.name %></h5>
              <p class="card-text">City: <span><%= accommodation.city %></span></p>
              <p class="card-text">State: <span><%= accommodation.state %></span></p>
              <p class="card-text">Address: <span><%= accommodation.address %></span></p>
              <p class="card-text">Pincode: <span><%= accommodation.pincode %></span></p>
              <%= link_to "View", accommodation_path(accommodation), class: "btn btn-primary" %>
              <%# Uncomment the line below if you want to include a delete button %>
              <%# link_to "Delete", accommodation_path(accommodation), data: { turbo_method: :delete, turbo_confirm: "are you sure to delete" }, class: "btn btn-outline-primary" %>
            </div>
          </div>
        </div>
       <% end %>
       <% else %>
       <p class="lead text-danger"> No Accommodation Available </p>
      <% end %>
    </div>
    <%= paginate @accommodations %>
  </div>
</div>

app/views/accommodations/show.html.erb
<div class="col-lg-12">
  <div class="justify-content-center">
    <div class="container">
      <div class="mx-auto card shadow mb-5">
        <% if @accommodation.galleries.attached? %>
          <%= image_tag @accommodation.galleries.first, style: "width: 100%; height: 350px;" %>
        <% end %>
        <div class="container">
          <div class="row">
            <div class="col-lg-6">
              <h5 class="card-title mt-3"><%= @accommodation.name %></h5>
              <p class="card-text">Contact number:<span class="ms-1"><%= @accommodation.contact_number %></span></p>
              <p class="card-text">Email:<span class="ms-1"><%= @accommodation.email %></span></p>
              <p class="card-text">City:<span class="ms-1"><%= @accommodation.city %></span></p>
              <p class="card-text">State:<span class="ms-1"><%= @accommodation.state %></span></p>
              <p class="card-text">Address:<span class="ms-1"><%= @accommodation.address %></span></p>
            </div>
            <div class="col-lg-6 my-5">
             <%= link_to "Book Room", new_accommodation_room_path(@accommodation), class: "btn btn-outline-danger" %>
             <% if current_user.rooms.where(accommodation: @accommodation, status: 'approved').exists? %>
                <%= link_to "View Our Rooms", accommodation_rooms_path(@accommodation), class: 'btn btn-primary' %>
              <% end %>

             <%# if current_user.rooms.where(accommodation: @accommodation, status: 'approved').present? %>
                <%#= link_to "View Our Rooms", accommodation_rooms_path(@accommodation), class: 'btn btn-primary' %>
              <%# end %>
           </div>
           <div class="col-lg-12 mt-3">
             <p class="card-text">About:<br><small><%= @accommodation.about %></small></p>
           </div>
         </div>
       </div>
       <div class="container mt-3 mb-3" id="Gallery">
          <% if  @accommodation.galleries.present? %>
             <h4 class="card-text text-center"><i>Hotel Views</i></h4>
          <% end %>
          <div class="row">
            <% @accommodation.galleries.each do |gallery| %>
              <% unless gallery == @accommodation.galleries.first %>
                <div class="col-lg-4">
                  <div class="card my-1">
                    <% if @accommodation.galleries.attached? %>
                      <%= image_tag gallery, style: "width: 100%; height: 350px;" %>
                    <% end %>
                  </div>
                </div>
              <% end %>
            <% end %>          
            <div class="mt-2">
              <% if current_user.admin? %>
                <%= link_to "Edit", edit_accommodation_path(@accommodation), class: "btn btn-primary" %>
                <%= link_to "Delete", accommodation_path(@accommodation), method: :delete, data: { confirm: "Are you sure to delete" }, class: "btn btn-outline-danger" %>
                <%= link_to "Back", places_path, class:"btn btn-outline-warning"%>
                <% end %>
            </div>
          </div>
        </div>
     </div>
   </div>
  </div>
</div>


<%#= render"rooms/form", room:@room%>

<div class="container mt-4" id="room">
  <h3 class="card-title text-center fs-2"><b>Available Room</b></h3>
  <p class="text-center">Just glance through these accommodations, and plan your trip with us for a memorable touring experience.</p>
  <div class="container ">
    <div class="row ">
      <div class="col-lg-4 text-center">
        <div class="position-relative">
          <%= image_tag("hotel_room_super.jpg", style:"width:100%; height:250px;max-height:250px;  ") %>
          <div class="position-absolute top-0 start-0 end-0 p-2 text-center"     style="background-color: rgba(0, 0, 0, 0.5); color: white;">
             <p>Deluxe Room</p>
          </div>
        </div>
      </div>
      <div class="col-lg-4 text-center">
        <div class="position-relative">
          <%= image_tag("hotel_room_delux.jpg",style:"width:100%; height:250px; max-height:250px;")%>
          <div class="position-absolute top-0 start-0 end-0 p-2 text-center" style="background-color: rgba(0, 0, 0, 0.5); color: white;">
            <p>Super Room</p>
          </div>
        </div>
      </div>
      <div class="col-lg-4 mb-5">
        <div class="position-relative">
          <%= image_tag("hotel_room_ptrenium.jpg",style:"width:100%; height:250px; max-height:250px;")%>
          <div class="position-absolute top-0 start-0 end-0 p-2 text-center" style="background-color: rgba(0, 0, 0, 0.5); color: white;">
            <p>Prenium</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="container" id="Amenities">
  <h2 class="mx-auto text-center fw-1">Amenities</h2>
  <div class="row ms-4 mt-5 d-flex justify-content-center ">
    <div class="col-lg-2 ">
      <i class="fa-solid fa-wifi  fs-1 ms-4"style="color: #ea7f1a;"></i><br>
      <p>Free internert</p>
    </div>
    <div class="col-lg-2">
      <i class="fa-solid fa-utensils fs-1 ms-5" style="color: #ea7f1a;"></i><br>
      <p>On-Site Restaurant</i></p>
    </div>
    <div class="col-lg-2">
      <i class="fa-solid fa-bell-concierge fs-1 ms-4" style="color: #ea7f1a;"></i></i><br>
      <p>Room Service</p>
    </div>
    <div class="col-lg-2">
      <i class="fa-solid fa-tv fs-1" style="color: #ea7f1a;"></i><br>
      <p class="ms-3">Tv</p>
    </div>
     <div class="col-lg-2">
      <i class="fa-solid fa-spa fs-1 me-3" style="color: #ea7f1a;"></i><br>
      <p>Spa</p>
    </div>
    
    <div class="col-lg-2">
      <i class="fa-solid fa-person-swimming fs-1 ms-1" style="color: #ea7f1a;"></i><br>
      <p>Pool</p>
    </div>
  </div>
  <div class="row mt-4 ms-4">
     <div class="col-lg-2">
      <i class="fa-solid fa-dumbbell fs-1 ms-3" style="color: #ea7f1a;"></i><br>
      <p>Fitness Center</p>
    </div>
     <div class="col-lg-2">
      <i class="fa-solid fa-handshake fs-1 ms-4" style="color: #ea7f1a;"></i><br>
      <p>Meeting Facilities</p>
    </div>
    <div class="col-lg-2">
      <i class="fa-solid fa-print fs-1 ms-4" style="color: #ea7f1a;"></i><br>
      <p>Business Services</p>
    </div>
    <div class="col-lg-2">
      <i class="fa-solid fa-car-on fs-1 " style="color: #ea7f1a;"></i><br>
      <p>Parking</p>
    </div>
    <div class="col-lg-2">
      <i class="fa-solid fa-sink fs-1" style="color: #ea7f1a;"></i><br>
      <p>Laundry</i></p>
    </div>
    <div class="col-lg-2 mx-auto">
      <i class="fa-solid fa-martini-glass-citrus fs-1 mx-auto" style="color: #ea7f1a;"></i><br>
      <p>Bars</p>
    </div>
  </div>
</div>