config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :inquiries
  root "places#index"
  get 'profile', to: 'profile#show'
  get 'search', to: 'search#search'
  resources :places
  resources :plan_your_trips
  resources :tourist_points
  resources :near_by_places
  resources :best_time_to_visits
  resources :how_to_reaches
  resources :car_rentals
  resources :papular_palaces
  resources :popular_places
  
  resources :accommodations do 
    resources :rooms
  end

  namespace :admin do 
    root "dashboard#show"
    get 'profile', to: 'profile#show'
    get 'search', to: 'search#search'
    resources :places
    resources :tourist_points
    resources :near_by_places
    resources :best_time_to_visits
    resources :how_to_reaches
    resources :accommodations
    resources :rooms
    resources :popular_places
    resources :plan_your_trips
    resources :inquiries
    resources :car_rentals do
      collection do
        get :car_all
      end
    end
    resources :rooms do
      member do
        put :approve
        put :unapprove
      end
    end
  end
end

app/models/place.rb
class Place < ApplicationRecord

  has_many_attached :images, dependent: :destroy
  has_rich_text :content
  has_many :near_by_places, dependent: :destroy
  has_many :tourist_points, through: :near_by_places, dependent: :destroy

  paginates_per 3 

  

   validates :state, :name, :district, :history, presence: true
   validates :latitude, :longitude, presence:true 
  #             uniqueness: { message: "latitude and longitude must be uniq" }

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "district", "history", "id", "latitude", "longitude", "name", "state", "updated_at","name", "distance_from", "location_name", "place_name", "histroy", "longitude", "latitude"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["images_attachments", "images_blobs", "rich_text_content"]
  end

end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < AdminController  
  layout 'admin'
  before_action :set_place, only: %i[ edit show update destroy ]

  def index
    @places = Place.includes(:tourist_points, images_attachments: :blob).page params[:page]
    arrange_order
  end 
 
  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      redirect_to admin_places_path , notice:"Place is add succesfully"
    else
      render :new
    end 
  end 

  def edit
  end

  def show
   @how_to_reaches = HowToReach.where(place_name: @place.name)
    @best_time_to_visits = BestTimeToVisit.all
    @tourist_points = TouristPoint.all
    @accommodations = Accommodation.all
    @near_by_places = @place.near_by_places
  end

  def update
    if @place.update(place_params)  
      redirect_to admin_places_path, notice:"Place is update"
    else
      render :edit
    end 
  end 

  def destroy
    if @place.destroy
      redirect_to admin_places_path, alert:"Place is delete succesfully"
    end
  end

  private

  def set_place
    @place = Place.includes(images_attachments: :blob).find(params[:id])
  end

  def place_params
    params.require(:place).permit(:state, :name, :district, :history , :latitude, :longitude, images: [])
  end

  def arrange_order
    @places = case params[:order]
      when 'asc'
      @places.order(created_at: :asc)
      when 'desc'
      @places.order(created_at: :desc)
     when 'A-Z'
      @places.order(name: :asc).group(:name).order("MIN(created_at) ASC")
     when 'Z-A'
      @places.order(name: :desc).group(:name).order("MIN(created_at) DESC")
      else
      @places.order(name: :desc) # Default sorting
   end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController 
  before_action :set_place, only: %i[ edit show update destroy ]

  def index
    @places = Place.includes(:tourist_points, images_attachments: :blob).page params[:page]
    arrange_order
  end 
 
  def show
   @how_to_reaches = HowToReach.where(place_name: @place.name)
    @best_time_to_visits = BestTimeToVisit.all
    @tourist_points = TouristPoint.all
    @accommodations = Accommodation.all
    @near_by_places = @place.near_by_places
  end

  private

  def set_place
    @place = Place.includes(images_attachments: :blob).find(params[:id])
  end

  def place_params
    params.require(:place).permit(:state, :name, :district, :history , :latitude, :longitude, images: [])
  end

  def arrange_order
    @places = case params[:order]
      when 'asc'
      @places.order(created_at: :asc)
      when 'desc'
      @places.order(created_at: :desc)
     when 'A-Z'
      @places.order(name: :asc).group(:name).order("MIN(created_at) ASC")
     when 'Z-A'
      @places.order(name: :desc).group(:name).order("MIN(created_at) DESC")
      else
      @places.order(name: :desc) # Default sorting
   end
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/admin/places/_form.html.erb
<%= form_with(model: [:admin, place], html: { data: { turbo: false } }) do |form| %>
	<%#= render 'shared/errors', model: @place %>
	<div class="form-outline mb-4">
		<%= form.label :name, class:"form-label" %>
		<%= form.text_field :name, class:"form-control" %>
		<% @place.errors.full_messages_for(:name).each do |message| %>
		<p class="text-danger"><%= message  %></p>
		<% end %>
	</div>

	<div class="form-outline mb-4">
		<%= form.label :state, class:"form-label" %>
		<%= form.text_field :state, class:"form-control" %>
		<% @place.errors.full_messages_for(:state).each do |message| %>
		<p class="text-danger"><%= message %></p>
		<% end %>
	</div>

	<div class="form-outline mb-4">
		<%= form.label :district, class:"form-label" %>
		<%= form.text_field :district, class:"form-control" %>
		<% @place.errors.full_messages_for(:district).each do |message| %>
		<p class="text-danger"><%= message %></p>
		<% end %>
	</div>

	<div class="row">
		<div class="col-lg-6">
			<div class="form-outline mb-4">
				<%= form.label :longitude, class:"form-label" %>
				<%= form.text_field :longitude, class:"form-control" %>
				<% @place.errors.full_messages_for(:longitude).each do |message| %>
				<p class="text-danger"><%= message %></p>
				<% end %>
			</div>
		</div>
		<div class="col-lg-6">
			<div class="form-outline mb-4">
				<%= form.label :latitude, class:"form-label" %>
				<%= form.text_field :latitude, class:"form-control"%>
				<% @place.errors.full_messages_for(:latitude).each do |message| %>
				<p class="text-danger"><%= message %></p>
				<% end %>
			</div>
		</div>
	</div>

	<div class="form-outline mb-4">
		<%= form.label :history, class:"form-label" %>
		<%= form.text_area :history, class:"form-control" %>
		<% @place.errors.full_messages_for(:history).each do |message| %>
		<p class="text-danger"><%= message %></p>
		<% end %>
	</div>

	<div class="form-outline mb-4">
		<%= form.label :images, class:"form-label" %>
		<%= form.file_field :images, multiple: true %>
		<% @place.errors.full_messages_for(:images).each do |message| %>
		<p class="text-danger"><%= message %></p>
		<% end %>
	</div>
	<%= form.submit "Submit" ,class:"btn btn-primary " %>
	<%= link_to "Back", places_path ,class:"btn btn-outline-warning" %>
<% end %>

app/views/admin/places/edit.html.erb
<div class="col-md-12 col-lg-8	mx-auto">
	<div class="container border-2 bg-light ">
		<div class="col-lg-12 col-sm-12">
			<h3 class="mt-2">Edit Page </h3>
			<%= render 'form', place: @place %>
		</div>
	</div>
</div>

app/views/admin/places/index.html.erb
<div class="col-lg-12">
  <%= link_to "Add Place", new_admin_place_path, class:"btn btn-primary"%>
  <% if @places.present? %>
    <div class="dropdown text-end mb-3">
      <a href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="text-decoration:none; color:black;">
       Filter
     </a>
     <ul class="dropdown-menu">
        <li><%= link_to "New", admin_places_path(order: 'asc'), style: "text-decoration: none; color:black;", class:"dropdown-item" %></li>
        <li><%= link_to "Old", admin_places_path(order: 'desc'), style: "text-decoration: none; color:black;", class:"dropdown-item" %></li>
        <li><%= link_to "A-Z", admin_places_path(order: 'A-Z'), style: "text-decoration: none; color:black;", class:"dropdown-item" %></li>
        <li><%= link_to "Z-A", admin_places_path(order: 'Z-A'), style: "text-decoration: none; color:black;", class:"dropdown-item" %></li>
      </ul>
    </div> 

    <% @places.each do |place| %>
      <%= link_to admin_place_path(place),style:"text-decoration:none; color:black;" do%>
      <div class="card mb-3" style="max-width: 800;">
        <div class="row g-0">
          <div class="col-md-4">
            <% if place.images.attached? %>
            <%= image_tag place.images.first, class: "img-fluid rounded-start place-img " %>
            <% end %>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title"><%= place.name %></h5>
              <h3 class="card-title"></h3>
              <p class="card-text"><%= simple_format(truncate(place.history, length: 200)) %></p> 
            </div>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
    <%= paginate @places %>
    <% else %>
    <p class="lead text-danger h3"> No data Found</p>
  <% end %>
</div>

<style>
  .place-img {
    width: 100%;
    height: 200px;
    max-height: 200px;
  }
</style>

app/views/admin/places/new.html.erb
<div class="col-md-12 col-lg-8	mx-auto">
	<div class="container border-2 bg-light ">
		<div class="col-lg-12 col-sm-12">
			<h3 class="mt-2">Add Place </h3>
			<%= render 'form', place: @place %>
		</div>
	</div>
</div>

app/views/admin/places/show.html.erb
<div class="col-lg-12">
  <div class="container">
    <div class="col-lg-12">
      <div class="container-fluid">
        <div class="card mb-4">
          <% if @place.images.attached? %>
          <%= image_tag @place.images[0], style: "width: 100%; height: 25rem;" %>          
          <% end %>
        </div>
        <h2><span class="ms-1"><%= @place.name %></span></h2>
        <p>State:<span class="ms-1"><%= @place.state %></span></p>
        <p>City:<span class="ms-1"><%= @place.district %></span></p>
        <div class="d-flex">
          <p>longitude:<span class="mx-1"><%= @place.longitude %></span></p>
          <p class="mx-5">latitude:<span class="mx-1"><%= @place.latitude %></span></p> 
        </div>
      </div>
    </div>
    <div class="col-lg-12">
      <div id="history-container"> <!-- Added container div -->
        <small ><%= simple_format(@place.history) %></small>
        <button id="toggle-history" class="btn btn-link">Show More</button>
      </div>
    </div>  
  </div>
</div>

<div class="container" id="tourist_places">
  <div class="card-deck">
    <% tourist_points = @place.tourist_points%>
    <% if tourist_points.present? %>
     <h3 class="text-center mt-3"> Tourist Place in <%= @place.name %></h3>
     <% @place.tourist_points.each do |tourist_point| %>

      <div class="card mt-2">
        <%= link_to admin_tourist_point_path(tourist_point), style: "text-decoration:none; color:black;" do %>
          <div class="row no-gutters ">
            <div class="col-md-4">
              <% if tourist_point.images.attached? %>
               <%= image_tag tourist_point.images.first, class: "card-img image-size", alt: "Place Image" %>
              <% end %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h3 class="card-title"><%= tourist_point.location_name %></h3>
                <p class="card-text"><%= simple_format(truncate(tourist_point.history, length: 200)) %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
     <% end %>
    <% end %>
  </div>
</div>


<div class="container " id="best_time_to_visit">
  <% best_time_to_visits = @best_time_to_visits.where(place_name: @place.name) %>
   <div class="mt-4">
      <% if best_time_to_visits.present? %>
        <h5 class=" fs-2 text-center">Best Time To Visit <%= @place.name %><span class="ms-3"></span></h5>
      <% end %>
     <div class="card-body">
      <% @best_time_to_visits.where(place_name: @place.name).each do |best_time_to_visit| %>
       <p class="card-text"><%= simple_format(best_time_to_visit.description) %></p>
      <% end %>
     </div> 
   </div>
</div>

<div class="container mt-4" id="how_to_rich">
  <div class="row">
    <% how_to_reaches = @how_to_reaches.where(place_name: @place.name) %>
    <% if how_to_reaches.present? %>
      <h3>How to Reach <%= @place.name %></h3>
      <% how_to_reaches.each do |how_to_reach| %>
        <div class="col-lg-4 justify-content-between ">
          <div class="container ">
            <div class="card mx-auto" style="width: 14rem;">
             <div class="card-body">
                <!-- <h5 class="card-title">Place:<span><%#= how_to_reach.place_name %></span></h5> -->
                <p class="card-header"><span><%= how_to_reach.title %></span></p>
                <p class="card-text mt-2"><span><%= how_to_reach.description %></span></p>
               </div>
            </div>
          </div>
       </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="container" id="Gallery">
  <% if  @place.images[1] %>
    <h3 class="m-2 mt-4">Gallery</h3>
 <% end %>
 <div class="row">
   <% @place.images.each do |image| %>
     <% unless image == @place.images[0] %>
       <div class="col-lg-4">
         <div class="card mb-2 mt-2">
           <a class="image-link" href="<%= rails_blob_path(image, only_path: true) %>" data-mfp-src="<%= rails_blob_path(image, only_path: true) %>" data-mfp-width="800" data-mfp-height="300">
             <%= image_tag image, style: "width: 800px; height: 300px; max-width: 100%;" %>
           </a>
         </div>
       </div>
     <% end %>
   <% end %>
 </div>
</div>

<div class="container" id="nearby-places">
  <% near_by_places = @place.near_by_places %>
  <% if near_by_places.present? %>   
   <h3 class="text-center mt-3">Near_by Places for <%= @place.name %></h3>
    <% @near_by_places.each do |near_by_place| %>
     <%= link_to admin_near_by_place_path(near_by_place), style: "text-decoration:none; color:black" do %>
       <div class="card mt-4" >
          <div class="row g-0">
            <div class="col-md-4 ">
              <% if near_by_place.images.attached? %>
              <%= image_tag near_by_place.images.first, class: "img-fluid rounded-start", style:"width:100%; height:180px;" %>
              <% end %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h2 class="card-title ms-3"><%= near_by_place.name %></h2>
                <h4 class="card-title ms-3"><%= near_by_place.city %></h4>
                <p class="card-text ms-3">
                 <%= near_by_place.distance_from %><span><%= near_by_place.place.name %></span>
               </p>
             </div>
           </div>
         </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

<div class="container mt-4 mb-4" id="accommodation">
  <% accommodations = @accommodations.where(city: @place.name) %>
  <% if accommodations.present? %>
    <h3 class="text-center mt-3 mb-3">Accommodation in <%= @place.name %></h3>
    <div class="row">
      <% accommodations.each do |accommodation| %>
        <div class="col-sm-6">
          <%= link_to(accommodation_path(accommodation), style: "text-decoration:none; color:black;", target: "_blank") do %>
            <div class="card">
              <% if accommodation.galleries.attached? %>
                <%= image_tag(accommodation.galleries.first, style: "width:100%; height:250px; max-width:100%; max-height:250px;", alt: "Place Image") %>
              <% end %>
              <div class="card-body">
                <h5 class="card-title"><%= accommodation.name %></h5>
                <div class="d-flex">
                  <p class="card-text"><%= accommodation.address %></p>
                  <p class="card-text"><%= accommodation.city %></p>
                </div>
                <p class="card-text"><%= accommodation.email %></p>
                <p class="card-text"><%= accommodation.contact_number %></p>
                <%#= link_to "Edit", edit_accommodation_path(accommodation), class: "btn btn-primary" %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
 <div class="container my-2">
   <%= link_to "Back", admin_places_path, class:"btn btn-outline-warning  " %>
   <% if current_user.admin? %>
     <%= link_to "Edit", edit_admin_place_path(@place), class:"btn btn-outline-primary " %>
     <%= link_to "Delete" , admin_place_path(@place) ,  data: {
     turbo_confirm: 'Are you Sure?', turbo_method: :delete }, class:"btn btn-outline-danger " %>
    <% end %>
  </div>
</div>
 

<style>
  .mfp-img {
      max-width: 800px !important;
      max-height: 800px !important;
    }
  .place-img{
   width: 100%;
   height: 200px;
   max-height: 200px;
   margin-top: 2px;
   margin-bottom: 0px;
  }
</style>

<script>
  $(document).ready(function() {
    var maxWords = 100; // Maximum number of words to display initially
    var historyContainer = $("#history-container");
    var historyText = historyContainer.find("small");
    var fullText = historyText.text();

    // Function to check if the history text has more than maxWords
    function hasMoreWords() {
      var words = fullText.split(' ');
      return words.length > maxWords;
    }

    // Function to trim and update the history text
    function trimText() {
      var words = fullText.split(' ');
      var trimmedText = words.slice(0, maxWords).join(' ');
      historyText.text(trimmedText);
    }

    // Initially trim the text
    trimText();

    // Show More button click event
    $("#toggle-history").click(function() {
      if (hasMoreWords()) {
        if ($(this).hasClass("showing-more")) {
          // If showing more, switch to showing less
          trimText();
          $(this).text("Show More");
          $(this).removeClass("showing-more");
        } else {
          // If showing less, display the full text
          historyText.text(fullText);
          $(this).text("Show Less");
          $(this).addClass("showing-more");
        }
      }
    });

    // Hide the button initially if there are not more than maxWords
    if (!hasMoreWords()) {
      $("#toggle-history").hide();
    }
  });
</script>