config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :inquiries
  root "places#index"
  get 'profile', to: 'profile#show'
  get 'search', to: 'search#search'
  resources :places
  resources :plan_your_trips
  resources :tourist_points
  resources :near_by_places
  resources :best_time_to_visits
  resources :how_to_reaches
  resources :car_rentals
  resources :papular_palaces
  resources :popular_places
  
  resources :accommodations do 
    resources :rooms
  end

  namespace :admin do 
    root "dashboard#show"
    get 'profile', to: 'profile#show'
    get 'search', to: 'search#search'
    resources :places
    resources :tourist_points
    resources :near_by_places
    resources :best_time_to_visits
    resources :how_to_reaches
    resources :accommodations
    resources :rooms
    resources :popular_places
    resources :plan_your_trips
    resources :inquiries
    resources :car_rentals do
      collection do
        get :car_all
      end
    end
    resources :rooms do
      member do
        put :approve
        put :unapprove
      end
    end
  end
end

app/models/accommodation.rb
class Accommodation < ApplicationRecord
	has_many_attached :galleries, dependent: :destroy
	has_many :rooms

	validates :name, :city, :state, :address, :pincode, :about, 
			  :contact_number,  presence: true
	# validates :email, presence: true, uniqueness: 
	          {message: "Email must be uniqe "}
	paginates_per 5
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/best_time_to_visit.rb
class BestTimeToVisit < ApplicationRecord
	validates :title, :place_name, :description, presence: true
	paginates_per 5
end

app/models/car_rental.rb
class CarRental < ApplicationRecord
	 validates :pick_up_location, :pick_up_date, :pick_up_time, :drop_off_location,
			  :drop_off_date, :drop_off_time, :car_type, :car_name, presence:true
end

app/models/how_to_reach.rb
class HowToReach < ApplicationRecord
	validates :title, :description, :place_name, presence:true
	paginates_per 6
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/near_by_place.rb
class NearByPlace < ApplicationRecord
	has_many_attached :images, dependent: :destroy
	belongs_to :place
	belongs_to :tourist_point

	 validates :tourist_point_id, :place_id, :city,
			  :name, presence:true 

	
	 validates :longitude, :latitude, presence:true


	

	def self.ransackable_attributes(auth_object = nil)
		["created_at", "distance_from", "id", "latitude", "longitude", "name", "place_id", "tourist_point_id", "updated_at" ,"state", "district", "history", "longitude", "latitude", "distance_from", "location_name", "place_name", "city"]
	end
	def self.ransackable_associations(auth_object = nil)
		["images_attachments", "images_blobs", "place", "tourist_point"]
	end
	
	paginates_per 5



	
end

app/models/place.rb
class Place < ApplicationRecord

  has_many_attached :images, dependent: :destroy
  has_rich_text :content
  has_many :near_by_places, dependent: :destroy
  has_many :tourist_points, through: :near_by_places, dependent: :destroy

  paginates_per 3 

  

   validates :state, :name, :district, :history, presence: true
   validates :latitude, :longitude, presence:true 
  #             uniqueness: { message: "latitude and longitude must be uniq" }

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "district", "history", "id", "latitude", "longitude", "name", "state", "updated_at","name", "distance_from", "location_name", "place_name", "histroy", "longitude", "latitude"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["images_attachments", "images_blobs", "rich_text_content"]
  end

end

app/models/plan_your_trip.rb
class PlanYourTrip < ApplicationRecord
	paginates_per 5
	validates :days_of_travel, :start_point_city, :travel_month, :name, :email , presence:true
end

app/models/popular_place.rb
class PopularPlace < ApplicationRecord
	has_many_attached :popular_place_images, dependent: :destroy
	paginates_per 5
	validates :name, :city, :state, :about, presence:true
end

app/models/room.rb
class Room < ApplicationRecord
	# has_many_attached :room_images, dependent: :destroy
	belongs_to :accommodation
	belongs_to :user

	paginates_per 5
	validates :title , :contact_number, :location, :room_number,  :adults, :childrens, :facilities, :price, presence:true

	validates :contact_number, presence: true, format: { with: /\A[6789]\d{9}\z/, message: "should start with 6789 and be 10 digits long" }

	 enum status: [:pending, :approved, :unapproved]	
end

app/models/search.rb
class Search < ApplicationRecord	
end

app/models/tourist_point.rb
class TouristPoint < ApplicationRecord
	has_many_attached :images, dependent: :destroy
	has_many :near_by_places, dependent: :destroy
	has_many :places, through: :near_by_places, dependent: :destroy

	validates :location_name, :place_name, :history , presence:true 
	validates :longitude , :latitude,  presence:true

	def self.ransackable_attributes(auth_object = nil)
		["created_at", "history", "id", "latitude", "location_name", "longitude", "place_name", "updated_at" ,"state", "name", "district", "distance_from", "longitude"]
	end
	def self.ransackable_associations(auth_object = nil)
		["images_attachments", "images_blobs", "near_by_places", "places"]
	end
	paginates_per 5
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, 
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_one_attached :user_image
  has_many :rooms
  validates :first_name, :last_name, :contact_number, :address, presence:true

  before_create :assign_role
  
  def name
    "#{first_name} #{last_name}"
  end


  #roles are define for user role
  ROLES = %w{admin user}

  #create run time role method 
  ROLES.each do |role_name| 
    define_method "#{role_name}?" do 
      role == role_name
    end
  end


  # omniauth login using google
  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first
    unless user
      user = User.create(
        email: data['email'],
        password: 'password' ,
        first_name: data['first_name'],
        last_name: data['last_name']
       )
    end
    user
  end

  private
  def assign_role
      self.role = 'admin' if email.ends_with?('@admin.com')
  end 
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
	def status_label(status)
		case status
		when 'approve'
			'Approve'
		when 'unapprove'
			'Unapprove'
		else 
			'Pending'
		end
	end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/shared/_admin_header.html.erb
<nav id="main-navbar" class="navbar navbar-expand-lg navbar-light bg-dark position-sticky">
  <div class="container-fluid ">
   <%= link_to "Historical Places", admin_root_path, class: "navbar-brand text-light" %>
    <div class="nav-item dropdown d-flex">
          <button class="btn text-light dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
             <i class="fa-regular fa-user fa-lg "></i>
          </button>
          <% if user_signed_in? %>
            <ul class="dropdown-menu">
              <li><%= link_to "sign out", destroy_user_session_path, method: :delete, class:"ms-2"  %></li>
              <li><%= link_to current_user.email, admin_profile_path , class: 'profile-link ms-2 ', style:"text-decoration:none; color:black;" %></li>
            </ul>
          <% end %>
         <%= form_with(url: admin_search_path, method: "get", local: true, id:"searchForm") do |form| %>
           <div class=" d-flex mb-2 ">
              <%= form.text_field :search, placeholder: "Search", class: "form-control  rounded",style:"min-width: 225px;"  %>
              <%= form.submit "Submit", class: "btn btn-outline-warning ms-2", id: "submitbutton", style: "display: none;"%>
            </div>
          <% end %>  
        </div>
        
  </div>
</nav>






<script type="text/javascript">
  $(document).ready(function (){
    $('#searchForm input[type="text"]').on('input',function (){
      if ($(this).val().trim() !== ''){
        $('#submitbutton').show();
      }
      else {
        $('#submitbutton').hide();
      }
    });
  });
</script>

app/views/shared/_delete_code.html.erb
<%#= search_form_for @q do |f| %>
  <%#= f.search_field :name_cont, placeholder: 'Search...' %>
  <%#= f.submit 'Search' %>
<%# end %>
 <% if @q %>
      <%= search_form_for @q, url: search_path, method: :get, class: "form-inline my-2 my-lg-0" do |f| %>
      <%= f.search_field :state_or_name_or_district_or_history_or_longitude_or_latitude_or_name_or_distance_from_or_location_name_or_place_name_or_history_or_longitude_or_latitude, class: "form-control me-2", placeholder: "Search..." %>
      <%= f.submit "Search", class: "btn btn-outline-primary my-2 my-sm-0" %>
      <% end %>

      <% end %>




<% if @q %>
<%= search_form_for @q, url: search_path, method: :get, class: "form-inline my-2 my-lg-0" do |f| %>
<%= f.search_field :state_or_name_or_district_or_history_or_longitude_or_latitude_or_name_or_distance_from_or_location_name_or_place_name_or_history_or_longitude_or_latitude, class: "form-control me-2", placeholder: "Search..." %>
<%= f.submit "Search", class: "btn btn-outline-primary my-2 my-sm-0" %>
<% end %>

<% end %>



  <% if @q %>
      <%= search_form_for @q, url: search_path, method: :get, class: "form-inline my-2 my-lg-0" do |f| %>
      <%= f.search_field :state_or_name_or_district_or_history_or_longitude_or_latitude_or_name_or_distance_from_or_location_name_or_place_name_or_history_or_longitude_or_latitude, class: "form-control me-2", placeholder: "Search..." %>
      <%= f.submit "Search", class: "btn btn-outline-primary my-2 my-sm-0" %>
      <% end %>

      <% end %>


 <!-- search controller  -->
<!-- class SearchController < ApplicationController
  def search
    
    @q = params[:q]
    
    # Search across all models and attributes
    @places = Place.ransack(
      name_or_description_cont: @q,
      state_cont: @q,
      district_cont: @q,
      history_cont: @q,     
      longitude_eq: @q,
      latitude_eq: @q
      ).result(distinct: true)

    @near_by_places = NearByPlace.ransack(
      name_cont: @q,
      distance_from_cont: @q,
      longitude_eq: @q,
      latitude_eq: @q
      ).result(distinct: true)

    @tourist_points = TouristPoint.ransack(
      location_name_cont: @q,
      place_name_cont: @q,
      history_cont: @q,
      longitude_eq: @q,
      latitude_eq: @q
      ).result(distinct: true)
  end
end
 -->

  @q = NearByPlace.ransack(params[:q])
    @near_by_places = @q.result(distinct: true)
  # Add debugging output to check the value of @near_by_places
  puts "NearByPlaces: #{@near_by_places.inspect}"


    @q = Place.ransack(params[:q])  # Set up @q here
    @places = @q.result(distinct: true)


    @q = TouristPoint.ransack(params[:q]) # Set up @q here
    @tourist_points = @q.result(distinct: true)




    Search.html.erb ka code he 

    <h1>Search Results</h1>

<h2>Places</h2>
<ul>
  <div class="col-lg-10 mx-auto mb-2">
    <% @places.each do |place| %>
    <div class="card shardow mx-auto mb-2" >
      <%= link_to place_path(place), style:"text-decoration: none;color:black; " do %>
      <h2 class="mx-3 mt-3 mb-3 text-dark"><span><%= place.id%></span>.<%= place.name %></h2>

      <% if place.images.attached? %>
      <%=  image_tag place.images.first, style:"width:100%; height:400px;", alt: "Place Image" %>
      <% end %>

      <div class="card-body">
        <p class="card-text"><%= simple_format(truncate(place.history, lenghth: 500))  %></p>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
</ul>

<h2>Nearby Places</h2>
<ul>
  <% @near_by_places.each do |near_by_place| %>
  <tr>
    <td class=""><%= near_by_place.tourist_point_id %></td>
    <td><%= near_by_place.place_id %></td>
    <td><%= near_by_place.name %></td>
    <td><%= near_by_place.longitude %></td>
    <td><%= near_by_place.latitude %></td>
    <td><%= near_by_place.distance_from %></td>
    <td><%= link_to "View", near_by_place , class:"btn btn-primary"%></td>
  </tr>
  <% end %>
</ul>

<h2>Tourist Points</h2>
<ul>
  <% @tourist_points.each do |tourist_point| %>
  <tr>
    <td><%= tourist_point.id%></td>
    <td><%= tourist_point.place_name%></td>
    <td><%= tourist_point.location_name %></td>
    <td><%= link_to "show", tourist_point, class:"btn btn-warning" %></td>
  </tr>
  <% end %>
</ul>



<!-- <form class="d-flex" role="search">
        <%# if @q %>
        <%#= search_form_for @q , url: :places, class: 'form-inline' do |f| %>
        # Attributes may be chained. Search multiple attributes for one value... 
        
        <%#= f.search_field :name_or_state_or_district_or_history_or_longitude_or_latitude_cont ,class:'form-control me-2 ', placeholder: "Search" %>
        <%#= f.submit class:"btn btn-outline-primary" %>
        <%# end %>
        <%# end %>
      </form>  -->




      <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "Navbar", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <!-- Add any other menu items you want -->
        </li>
      </ul>

      <%= form_tag search_path, method: :get, class: "form-inline my-2 my-lg-0" do %>
      <%= text_field_tag :q, params[:q], class: "form-control me-2", placeholder: "Search..." %>
      <%= submit_tag "Search", class: "btn btn-outline-primary my-2 my-sm-0" %>
      <% end %>

    </div>
  </div>
</nav>

<p>@import "trix/dist/trix"</p>
<% if @place.history.length > 200 %>
            <small><%= simple_format(truncate(@place.history, length: 200)) %>
              <%= link_to '...Read more', '#', class: "read-more-<%= @place.id %>" %>
            </small>
            <script>
              $('.read-more-<%= @place.id %>').on('click', function(e) {
                e.preventDefault();
                $(this).parent().html('<%= escape_javascript @place.history %>');
              });
            </script>
          <% else %>
            <%= @place.history %>
          <% end %>
        </div>

 $(document).ready(function(){
   const historyContainer = $("#history-container");
   const toggleButton = $("#toggle-history");

   const historyText = historyContainer.find("small").text();
const maxWords = 100; // Change this to the desired word count
let isExpanded = false; // Initially not expanded

function toggleHistory() {
  isExpanded = !isExpanded;
  // !isExpanded = isExpanded;

  if (!isExpanded) {
    historyContainer.find("small").text(historyText);
    toggleButton.text("Show Less");
  } else {
    const truncatedText = historyText.split(' ').slice(0, maxWords).join(' ');
    historyContainer.find("small").text(truncatedText + '....');
    toggleButton.text("Show More");
  }
}

toggleButton.click(toggleHistory);

// Initial state: Show 200 words initially
toggleHistory();

    // gallery
$('.image-link').magnificPopup({
  type: 'image',
  gallery: {
    enabled: true
  },  
});
});

app/views/shared/_errors.html.erb
<% if model.errors.any? %>
<div id="error_explanation">
	<p><%= pluralize(model.errors.count,"error") %> prohibited this <% model %> from being saved </p>
	<ul>
		<% model.errors.each do |error| %>
		<li class="text-danger"><%= error.full_message %></li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/shared/_flash.html.erb
<div id="flash">
	<% flash.each do |key, value| %>
		<div class=" <%= flash_class(key.to_sym) %> alert-dismissible fade show mt-1" role= "alert">
			<% unless value == true %>
			<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			<%= value %>
			<% end %>
		</div>
	<% end %>	
</div>

app/views/shared/_header.html.erb
 <% if user_signed_in? %>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <% if current_user.admin? %>
      <%= link_to "Historical Places", admin_root_path, class: "navbar-brand" %>
      <% else %>
      <%= link_to "Historical Places", root_path, class: "navbar-brand" %>
   <% end %>
   <button class="navbar-toggler" type="button" data-bs-toggle="collapse"       data-bs-target="#navbarSupportedContent" aria-controls="  navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span>
   </button>
   <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-0  mb-lg-0 ">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-light " href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           Explore
         </a>
         <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          
               <li><%= link_to "Tourist Point", tourist_points_path, class: "dropdown-item" %></li>
              
              <li><%= link_to "Nearby Place", near_by_places_path, class: "dropdown-item" %></li>
              <li><%= link_to "How to Reach", how_to_reaches_path, class: "dropdown-item" %></li>
              <li><%= link_to "Best Time to Visit", best_time_to_visits_path, class: "dropdown-item" %></li>
              <li><%= link_to "Accommodation", accommodations_path, class: "dropdown-item" %></li>
              <li><%#= link_to "Room", rooms_path, class: "dropdown-item" %></li>
              <li><%= link_to "plan your trip", plan_your_trips_path, class: "dropdown-item" %></li>
              <li><%= link_to "car rental", car_rentals_path, class: "dropdown-item" %></li>
              <li><%= link_to "Popular Place", popular_places_path, class: "dropdown-item" %></li>
         </ul>
     <li class="text-end"><%= link_to "Inquiry Form", new_inquiry_path, class: "dropdown-item text-light mt-2 " %></li>
        </li>
     </ul>
     <div class="dropdown mt-0 mb-1 ">
          <button class="btn text-light dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
           <i class="fa-regular fa-user fa-lg "></i>
         </button>
         <% if user_signed_in? %>
           <ul class="dropdown-menu">
              <li><%= link_to "sign out", destroy_user_session_path, method: :delete, class:"ms-3"  %></li>
              <li><%= link_to current_user.email, profile_path , class: 'profile-link ms-3', style:"text-decoration:none; color:black;" %></li>
            </ul>
         <% end %>
     </div>
     <%= form_with(url: admin_search_path, method: "get", local: true, id:"searchForm") do |form| %>
        <div class=" d-flex mb-2 ">
          <%= form.text_field :search, placeholder: "Search", class: "form-control me-2"  %>
          <%= form.submit "Submit", class: "btn btn-outline-warning", id: "submitbutton", style: "display: none;"%>
       </div>
      <% end %>  
    </div>
  </div>
</nav>
<% end %>


<script type="text/javascript">
  $(document).ready(function (){
    $('#searchForm input[type="text"]').on('input',function (){
      if ($(this).val().trim() !== ''){
        $('#submitbutton').show();
      }
      else {
        $('#submitbutton').hide();
      }
    });
  });
</script>

app/views/shared/_sidebar.html.erb
<div class="position-sticky ">
  <div class="list-group list-group-flush mx-3">
    <a href="#" class="list-group-item list-group-item-action py-2 ripple" aria-current="true">
      <i class="fas fa-tachometer-alt fa-fw me-3 mt-2"></i><span>Main dashboard</span>
    </a>
    <div class="mb-3">
      <span><%= link_to "Tourist Point", admin_tourist_points_path, class: "list-group-item list-group-acion py-2 ripple" %></span>
      <span><%= link_to "Place", admin_places_path, class: "list-group-item list-group-acion py-2 ripple" %></span>
      <span><%= link_to "Nearby Place", admin_near_by_places_path, class: "list-group-item list-group-acion py-2 ripple" %></span>
      <span><%= link_to "How to Reach", admin_how_to_reaches_path, class: "list-group-item list-group-acion py-2 ripple" %></span>
      <span><%= link_to "Best Time to Visit", admin_best_time_to_visits_path, class: "list-group-item list-group-acion py-2 ripple" %></span>
      <span><%= link_to "Accommodation", admin_accommodations_path, class: "list-group-item list-group-acion py-2 ripple" %></span>
      <span><%= link_to "Plan Your Trip", admin_plan_your_trips_path, class: "list-group-item list-group-acion py-2 ripple" %></span>
      <span><%= link_to "Car Rental", admin_car_rentals_path, class: "list-group-item list-group-acion py-2 ripple" %></span>
      <span><%= link_to "Popular Place", admin_popular_places_path, class: "list-group-item list-group-acion py-2 ripple" %></span>
      <span><%= link_to "Inquiry", admin_inquiries_path, class: "list-group-item list-group-acion py-2 ripple" %></span>
      <span><%= link_to "Room Request", admin_rooms_path, class: "list-group-item list-group-acion py-2 ripple" %></span>
    </div>
  </div>
</div>